language: node_js

cache:
  directories:
    - ~/.npm

notifications:
  email: false

node_js:
  - '8'
  - '10'
  - '12'

script: npm run test:prod

jobs:
  include:
    - stage: lint
      node_js: '12'
      script: npm run lint
    - stage: deploy
      node_js: '12'
      script:
        - npm run build
        - npm run deploy-docs
        - npm run semantic-release
      if: branch = master

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
