language: node_js
cache:
  directories:
  - "~/.npm"
notifications:
  email: false
node_js:
- '8'
- '10'
- '12'
script: npm run test:prod
jobs:
  include:
  - stage: deploy
    node_js: '12'
    script: npm run lint && npm run build
    deploy:
      - provider: pages
        skip_cleanup: true
        github_token: "$GH_TOKEN"
        keep_history: true
        verbose: true
        on:
          branch: master
      - provider: releases
        api_key: "$GH_TOKEN"
        skip_cleanup: true
        on:
          tags: true
          branch: master
      - provider: npm
        email: eliseumds@gmail.com
        api_key:
          secure: jxiN7JX1CFt/MLLZcLZPlTxhP7iCnTdyf5u3k23RVkGModpmFtObFn8xBRpLueDeLBXQFMiwhzhWjJbHWcSEvfGfbOseC5Yzk31cM+XxkjHgm+m94MVwWJyc7mAvePWlMKQM6LNiDij6xgf1CR89RiFJ/7zIZAQm366bfFFWSXfv3MU8LUERJfa7Mf9ZSoK2etCs0gdrMpOyyYu7CKVCfOK3rIzi+uf9zC2solDgkt4nEUyswF2XLkeC6943wV2VvsMrLoS1JDeDaFleuSOcvs/eAmHtDVvOLN3wdFN32CQj/OD0bSlzffyX6SC76m4OF8dSkbUoIR/S5CPRFavvMYQ6weTFKjNvvU6s8FLBR0+Zq7PShMJu7+iJJan9NlMdbQNyBGqqjQNZ9FG1+OCu+x1DPZvIM4PaMOKkDF7B8x4sxwG2fL2riZSkQ88vEHxvL8m/94/81fITJenOVK34mZ4kp6ixUWjiIELBv4ye/rXCcsKdT9phSne6XozzJTZQmDO8IOJQSMRSxsCoWuagsGGLH1tOdOOlCzMm8UJvDMay/TDqu6suLxRu7vil4TTX4FlejOAA1GYIlkS7s6f3mVmD3PzH0HEiDHpjcolAbVUrZVFCe5LMiok2Q1P6c8iWy1pi1uzPJjZCLmMAEyvaG8OM8ST6nYpUo4ZOfZG6WWI=
        on:
          tags: true
          branch: master

branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
