const { cd, exec, echo, touch } = require("shelljs")
const { existsSync, readFileSync } = require("fs")
const url = require("url")

if (!existsSync('./docs/js/demo.js')) {
  throw new Error('tools/gh-pages-publish: run "npm run build" before');
}

let repoUrl
let pkg = JSON.parse(readFileSync("package.json") as any)
if (typeof pkg.repository === "object") {
  if (!pkg.repository.hasOwnProperty("url")) {
    throw new Error("URL does not exist in repository section")
  }
  repoUrl = pkg.repository.url
} else {
  repoUrl = pkg.repository
}

let parsedUrl = url.parse(repoUrl)
let repository = (parsedUrl.host || "") + (parsedUrl.path || "")
let ghToken = process.env.GH_TOKEN

echo("Deploying docs!!!")
exec("git add .") // add whatever files were generated by the build script
exec('git config user.name "Eliseu dos Santos"')
exec('git config user.email "eliseumds@gmail.com"')
exec('git commit -m "docs(docs): update gh-pages"')
exec(
  `git push --force --quiet "https://${ghToken}@${repository}" master:gh-pages`
)
echo("Docs deployed!!")
