const { cd, exec, echo, touch } = require('shelljs')
const { existsSync, readFileSync } = require('fs')
const url = require('url')

if (!existsSync('./docs/js/demo.js')) {
  throw new Error('tools/gh-pages-publish: run "npm run build" before');
}

let repoUrl
let pkg = JSON.parse(readFileSync('package.json') as any)
if (typeof pkg.repository === 'object') {
  if (!pkg.repository.hasOwnProperty('url')) {
    throw new Error('URL does not exist in repository section')
  }
  repoUrl = pkg.repository.url
} else {
  repoUrl = pkg.repository
}

let parsedUrl = url.parse(repoUrl)
let repository = (parsedUrl.host || '') + (parsedUrl.path || '')
let ghToken = process.env.GH_TOKEN

echo(`Deploying docs to ${repository}`)
exec('git config user.name "TravisCI"')
exec('git config user.email "travis@travis-ci.org')
exec('git checkout gh-pages')
exec('git add .') // add whatever files were generated by the build script
exec('git commit -m "docs(docs): update gh-pages. Travis build $TRAVIS_BUILD_NUMBER"')
exec(`git remote add origin-pages https://${ghToken}@${repository} > /dev/null 2>&1`)
exec('git push --quiet --set-upstream origin-pages gh-pages');
echo('Docs deployed!!')
